# Generated by Django 3.1.3 on 2021-10-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20211027_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('orcamento', 'cliente', '-date', 'hora', '-priority', 'event')},
        ),
    ]
