# Generated by Django 3.1.3 on 2022-06-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20211031_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
