# Generated by Django 3.1.3 on 2022-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20220604_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
